spring:
  profiles:
    active: aws
  application:
    name: CodeGuru

server:
  port: 9000

cloud:
  aws:
    stack:
      auto: false
    credentials:
      instanceProfile: true
      useDefaultAwsCredentialsChain: true
    region:
      static: us-west-1

aws:
  region: eu-west-1
  username: code_guru
  accessKey: AKIA6JSI75KLW5U63ENH
  secretKey: /im/HSrR4DqY/FHh6GrEbzj8h3HfRRD48LUGVvN
  profiling:
    group:
      name: CDI_AG